# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Shadi Abudalfa"
  headline: "Research Scientist at King Fahd University of Petroleum & Minerals"
  email: "shadi.abudalfa@kfupm.edu.sa"
  location: null
  profileImage: "https://github.com/sabudalfa.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/shadiabudalfa"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Resume"
      url: "/pdf/CV.pdf"
      icon:
        name: "FaRegIdBadge"
        package: "react-icons/fa6"
        
    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=hUnnZTQAAAAJ&hl"
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    - name: "ResearchGate"
      url: "https://www.researchgate.net/profile/Shadi-Abudalfa"
      icon:
        name: "FaResearchgate"
        package: "react-icons/fa6"
        
    - name: "ORCID"
      url: "https://orcid.org/0000-0002-2028-144X"
      icon:
        name: "LiaOrcid"
        package: "react-icons/lia"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
     Shadi Abudalfa received his BSc and MSc degrees in Computer Engineering from the Islamic University of Gaza (IUG), Palestine, in 2003 and 2010, respectively. He earned his PhD in Computer Science and Engineering from King Fahd University of Petroleum & Minerals (KFUPM), Saudi Arabia, in 2018 on a full-student scholarship. Abudalfa has extensive teaching experience, having worked as an assistant professor at the University College of Applied Sciences, Palestine. He is currently a research scientist at KFUPM. From July 2003 to August 2004, he served as a research assistant at the Projects and Research Lab at IUG and simultaneously worked as a teaching assistant in the Faculty of Engineering. He has reviewed for numerous international conferences and journals and has served as a guest editor for Frontiers in Artificial Intelligence. His contributions include several research publications and a patent. Additionally, he has been a PI and Co-I in some funded projects. His research interests focus on data mining, human activity recognition, and Arabic natural language processing.

# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "PhD in Computer Science and Engineering"
    school: "King Fahd University of Petroleum & Minerals"
    years: "2013 - 2018"
    logo: "https://upload.wikimedia.org/wikipedia/ar/archive/3/37/20221103091849%21King_Fahd_University_of_Petroleum_%26_Minerals_Logo.png"

  - degree: "MSc in Computer Engineering"
    school: "Islamic University of Gaza"
    years: "2007 - 2010"
    logo: "/images/IUGaza.png"

  - degree: "BSc in Computer Engineering"
    school: "Islamic University of Gaza"
    years: "1998 - 2003"
    logo: "/images/IUGaza.png"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "Research Scientist"
    company: "King Fahd University of Petroleum & Minerals"
    years: "2023 - Present"
    logo: "https://upload.wikimedia.org/wikipedia/ar/archive/3/37/20221103091849%21King_Fahd_University_of_Petroleum_%26_Minerals_Logo.png"

  - title: "Assistant Professor (Full-Time)"
    company: "University College of Applied Sciences"
    years: "August 2019 - July 2023"
    logo: "/images/UCAS.png"

  - title: "Assistant Professor (Part-Time)"
    company: "Islamic University of Gaza"
    years: "September 2019 - January 2022"
    logo: "/images/IUGaza.png"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

talks:
  - category: "Conference"
    title: "Entity Sentiment Classification using Arabic Lightweight LLMs"
    organization: "EngiTek"
    date: "December 31, 2025"
    link: "https://www.just.edu.jo/Conferences/EngiTek2025/Pages/Program-Day-3.aspx"
    image: null
    
  - category: "Conference"
    title: "Empirical Analysis for Detecting Arabic Online Suicidal Ideation"
    organization: "ACLing"
    date: "October 25, 2024"
    link: null
    image: null

  - category: "Conference"
    title: "Hybrid Deep-readout Echo State Network and Support Vector Machine with Feature Selection for Human Activity Recognition"
    organization: "EAI WiCON"
    date: "December 11, 2020"
    link: "https://wicon.eai-conferences.org/2020/accepted-papers"
    image: null

  - category: "Conference"
    title: "Deep Learning for Target-Dependent Sentiment Classification in Social Media"
    organization: "Smart Cities Symposium"
    date: "April 23, 2018"
    link: null
    image: null

# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

services:
  - category: "Research"
    role: "Master‚Äôs Thesis Defense Member"
    organization: "IUG"
    date: "2021 - current"
    link: null
    image: null

  - category: "Research"
    role: "Guest editor"
    organization: "Frontiers in Artificial Intelligenc"
    date: "2024-2025"
    link: null
    image: null

  - category: "Research"
    role: "Reviewer"
    organization: "Various International Journals"
    date: "2019 - current"
    link: null
    image: null

  - category: "Research"
    role: "Shared Task Organizer"
    organization: "AbjadNLP, ArabicNLP"
    date: "2025, 2026"
    link: "https://aclanthology.org/2025.arabicnlp-sharedtasks.1"
    image: null

  - category: "Research"
    role: "Doctoral Colloquium Co-Chair"
    organization: "IE 2026"
    date: "2026"
    link: "https://ie2026.pt/index.php/doctoral-colloquium"
    image: null   

  - category: "Research"
    role: "Program Co-Chair"
    organization: "SaudiCIS"
    date: "2024"
    link: "https://events.kfupm.edu.sa/event/220/page/131-program-co-chairs"
    image: null     

  - category: "Teaching"
    role: "Instructor"
    organization: "IUG, UCAS, KFUPM"
    date: "2004-2026"
    link: null
    image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "C"
      logo: "https://upload.wikimedia.org/wikipedia/commons/3/35/The_C_Programming_Language_logo.svg"
      proficiency: Experienced
      description: null

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Experienced
      description: null

    - name: "JavaScript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

  Machine Learning:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
      proficiency: Experienced
      description: null

    - name: "TensorFlow"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg"
      proficiency: Experienced
      description: null

    - name: "Keras"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
      proficiency: Experienced
      description: null

  Research:
    - name: "Machine Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2020 - Current
      description: "Deep learning methods and applied research."

    - name: "Large Language Models"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2023 - Current
      description: "Using LLMs with different learning settings."

  Language:
    - name: "English"
      logo: null
      proficiency: Highly proficient
      description: "Professional working proficiency."

    - name: "Arabic"
      logo: null
      proficiency: Native
      description: "Native fluency."
