# =====================================================
# Data displayed on the Home (About Me) page.
#
# üí° Tip for Images / Logo:
# You can use either:
# 1. A full URL (e.g., https://example.com/logo.png)
# 2. A local file placed under /public/images/ and referenced with "/" (e.g., "/images/logo.png")
# =====================================================

# =====================================================
# üë§ Personal Information
# =====================================================

profile:
  name: "Shadi Abudalfa"
  headline: "Research Scientist at King Fahd University of Petroleum & Minerals"
  email: "shadi.abudalfa@kfupm.edu.sa"
  location: null
  profileImage: "https://github.com/sabudalfa.png"

  links:
    - name: "LinkedIn"
      url: "https://www.linkedin.com/in/shadiabudalfa"
      icon:
        name: "FaLinkedin"
        package: "react-icons/fa6"

    - name: "Google Scholar"
      url: "https://scholar.google.com/citations?user=hUnnZTQAAAAJ&hl"
      icon:
        name: "FaGoogleScholar"
        package: "react-icons/fa6"

    - name: "ResearchGate"
      url: "https://www.researchgate.net/profile/Shadi-Abudalfa"
      icon:
        name: "FaResearchgate"
        package: "react-icons/fa6"

  # you can use HTML syntax here (e.g. <br/>, <a>, <strong>, ...)
  biography: |
     Shadi Abudalfa received his BSc and MSc degrees in Computer Engineering from the Islamic University of Gaza (IUG), Palestine, in 2003 and 2010, respectively. He earned his PhD in Computer Science and Engineering from King Fahd University of Petroleum & Minerals (KFUPM), Saudi Arabia, in 2018 on a full-student scholarship. Abudalfa has extensive teaching experience, having worked as an assistant professor at the University College of Applied Sciences, Palestine. He is currently a research scientist at KFUPM. From July 2003 to August 2004, he served as a research assistant at the Projects and Research Lab at IUG and simultaneously worked as a teaching assistant in the Faculty of Engineering. He has reviewed for numerous international conferences and journals and has served as a guest editor for Frontiers in Artificial Intelligence. His contributions include several research publications and a patent. Additionally, he has been a PI and Co-I in some funded projects. His research interests focus on data mining, human activity recognition, and Arabic natural language processing.

# # =====================================================
# # üéì Education Section
# # =====================================================

education:
  - degree: "Ph.D. in [Field]"
    school: "[University Name]"
    years: "20XX - Present"
    logo: "https://upload.wikimedia.org/wikipedia/en/a/a1/Arizona_State_University_seal.svg"

  - degree: "M.S. in Computer Science"
    school: "National Taiwan University"
    years: "2020 - 2022"
    logo: "/images/ntu_logo.svg"

  - degree: "B.S. in Computer Science"
    school: "National Chengchi University"
    years: "2018 - 2020"
    logo: "/images/nccu_logo.svg"

# # =====================================================
# # üíº Work Experience Section
# # =====================================================

workExperience:
  - title: "[Job Title]"
    company: "[Company Name]"
    years: "20XX - Present"
    logo: "/images/nvidia_logo.webp"

  - title: "Software Engineering Intern"
    company: "Google"
    years: "Jul 2022 - Sep 2022"
    logo: "/images/google_logo.svg"

  - title: "Research Assistant"
    company: "University of Illinois Urbana-Champaign"
    years: "Jul 2019 - Sep 2019"
    logo: "/images/uiuc_logo.png"

# # =====================================================
# # üé§ Presentations / Talks Section
# # =====================================================

talks:
  - category: "Misc"
    title: "[Your Talk Title Here]"
    organization: "[Your Talk Location Here]"
    date: "[Month Day, Year]"
    link: "https://example.com/your-talk-link"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Workshop"
    title: "Deep Learning with Keras"
    organization: "University of Illinois Urbana-Champaign (UIUC)"
    date: "Sep 4, 2019"
    link: null
    image: "https://pm25.github.io/images/uiuc-workshop.webp"

  - category: "Workshop"
    title: "Practical Guide to PyTorch"
    organization: "ABC University"
    date: "Dec 5, 2022"
    link: "https://example.com/workshop-talk"
    image: null

# # =====================================================
# # üõ°Ô∏è Professional Services
# # =====================================================

services:
  - category: "Misc"
    role: "[Role]"
    organization: "[Organization]"
    date: "[Year]"
    link: "https://example.com/workshop-talk"
    image: "https://upload.wikimedia.org/wikipedia/commons/8/8f/Example_image.svg"

  - category: "Research"
    role: "Reviewer"
    organization: "TPAMI 2024, NeurIPS 2025"
    date: "2024-2025"
    link: null
    image: null

  - category: "Research"
    role: "Program Committee Member"
    organization: "CVPR 2022"
    date: "2022"
    link: null
    image: null

  - category: "Teaching"
    role: "Teaching Assistant"
    organization: "National Taiwan University - Data Structures & Algorithms"
    date: "2021"
    link: null
    image: null

# # =====================================================
# # üõ†Ô∏è Skills Section
# # =====================================================

skills:
  Programming:
    - name: "[Name]"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/18/ISO_C%2B%2B_Logo.svg"
      proficiency: "[Proficiency]"
      description: "[Description]"

    - name: "Python"
      logo: "https://upload.wikimedia.org/wikipedia/commons/c/c3/Python-logo-notext.svg"
      proficiency: Experienced
      description: null

    - name: "JavaScript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/9/99/Unofficial_JavaScript_logo_2.svg"
      proficiency: Fluent
      description: null

  Web:
    - name: "React"
      logo: "https://upload.wikimedia.org/wikipedia/commons/3/30/React_Logo_SVG.svg"
      proficiency: Advanced
      description: null

    - name: "Typescript"
      logo: "https://upload.wikimedia.org/wikipedia/commons/f/f5/Typescript.svg"
      proficiency: Fluent
      description: null

    - name: "TailwindCSS"
      logo: "https://upload.wikimedia.org/wikipedia/commons/d/d5/Tailwind_CSS_Logo.svg"
      proficiency: Fluent
      description: null

    - name: "Next.js"
      logo: "https://logo.svgcdn.com/devicon/nextjs-original.png"
      proficiency: Fluent
      description: null

  Machine Learning:
    - name: "PyTorch"
      logo: "https://upload.wikimedia.org/wikipedia/commons/1/10/PyTorch_logo_icon.svg"
      proficiency: Experienced
      description: null

    - name: "TensorFlow"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2d/Tensorflow_logo.svg"
      proficiency: Fluent
      description: null

    - name: "Keras"
      logo: "https://upload.wikimedia.org/wikipedia/commons/a/ae/Keras_logo.svg"
      proficiency: Fluent
      description: null

  Research:
    - name: "Machine Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2020 - Current
      description: "General machine learning methods and applied research."

    - name: "Representation Learning"
      logo: "https://upload.wikimedia.org/wikipedia/commons/2/2a/OOjs_UI_icon_academic-progressive.svg"
      proficiency: 2024 - 2025
      description: "Learning meaningful embeddings and feature representations from data."

  Language:
    - name: "English"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Fluent
      description: "Professional working proficiency."

    - name: "Taiwanese Hokkien"
      logo: "https://upload.wikimedia.org/wikipedia/commons/e/e0/OOjs_UI_icon_language-ltr-progressive.svg"
      proficiency: Native
      description: "Native fluency."
