# =====================================================
# Project data displayed on the Projects page.
#
# This section automatically fetches project information from your GitHub repositories.
#
# ✔ The `id` field should be the exact repository name
#    (e.g., from: github.com/<your-username>/<repo-name>)
#
# ✔ The `displayName` field controls how the project name appears on the website.
#
# ✔ Use the `featured` field to control which projects appear on the homepage.
#    - featured: true  → shown on the homepage
#    - featured: false → shown only on the Projects page
# =====================================================

projects:
  items:
    - id: "ArabicTextSentimentSwap" # name of your GitHub repository (from: github.com/<your-username>/<repo-name>)
      displayName: "Arabic Text Sentiment Swap" # name that will be displayed on the website
      previewImage: null
      featured: true

    - id: "AT-ODTSA"
      displayName: "Arabic Open Domain Targeted Sentiment Analysis"
      previewImage: null
      featured: true

    - id: "ArabicTextFormalityTransfer"
      displayName: "Arabic Text Formality Transfer"
      previewImage: null
      featured: true

    - id: "HumanActivityRecognition"
      displayName: "Human Activity Recognition"
      previewImage: null
      featured: true

    - id: "AT-ODTSA"
      displayName: "Dataset of Arabic Tweets for Open Domain Targeted Sentiment Analysis"
      previewImage: null
      featured: true

    - id: "Target-DependentSentimentClassification"
      displayName: "Target-Dependent Sentiment Classification"
      previewImage: null
      featured: true

    - id: "DataClusteringAlgorithms"
      displayName: "DataClusteringAlgorithms"
      previewImage: null
      featured: true
