# =====================================================
# Publications data displayed on the Publications page.
#
# `authorName`:
#   - Fill in *your* name exactly as it appears in author lists.
#   - Your name will be highlighted automatically in all publication entries.
#
# `items`:
#   - Each item represents one publication.
#   - `title`: Full title of the publication.
#   - `authors`: List of authors as a single string, separated by commas.
#   - `year`: Publication year.
#   - `venue`: Conference or journal name.
#   - `link`: URL to the paper (ArXiv, DOI, PDF, etc.).
#   - `featured`:
#       true  → shown on homepage (highlighted)
#       false → shown only on Publications page
# =====================================================

publications:
  authorName: "Shadi Abudalfa" # Your name here (to highlight your name in publications)

  items:

  # ======================
  # Journal Papers
  # ======================

      - title: "MA’AKS: Manually-Curated Parallel Dataset for Arabic Text Sentiment Swap"
        authors: "Raed Mughaus, Shadi Abudalfa, Hamzah Luqman, Fahad Abdu, Mohammed AlAli, Nawaf Al-Dowayan, Ahmed Abdelali"
        year: 2025
        venue: "Language Resources and Evaluation"
        link: "https://link.springer.com/article/10.1007/s10579-025-09895-4"
        featured: true
    
      - title: "An Empirical Evaluation of Arabic Text Formality Transfer: A Comparative Study"
        authors: "Fahad J. Abdu, Raed Mughaus, Shadi Abudalfa, Moataz Ahmed, Ahmed Abdelali"
        year: 2025
        venue: "Language Resources and Evaluation"
        link: "https://link.springer.com/article/10.1007/s10579-025-09873-w"
        featured: true
    
      - title: "A Hybrid Vision Transformer and Residual Neural Network Model for Fall Detection Using UWB Radars"
        authors: "Shadi Abudalfa, Kevin Bouchard"
        year: 2025
        venue: "Applied Intelligence"
        link: "https://link.springer.com/article/10.1007/s10489-024-06156-9"
        featured: true
    
      - title: "Dual Pipeline Technique for Detecting Sepsis from Photoplethysmography"
        authors: "Shadi Abudalfa, Sara Lombardi, Eleonora Barcali, Leonardo Bocchi"
        year: 2025
        venue: "International Journal of Data Mining and Bioinformatics"
        link: "https://www.inderscienceonline.com/doi/abs/10.1504/IJDMB.2025.147058"
        featured: true

      - title: "The AraGenEval Shared Task on Arabic Authorship Style Transfer and AI Generated Text Detection"
        authors: "Shadi Abudalfa, Saad Ezzini, Ahmed Abdelali, Hamza Alami, Abdessamad Benlahbib, Salmane Chafik, Mo El-Haj, Abdelkader El Mahdaouy, Mustafa Jarrar, Salima Lamsiyah, Hamzah Luqman"
        year: 2025
        venue: "ArabicNLP"
        link: "https://underline.io/lecture/137113-the-arageneval-shared-task-on-arabic-authorship-style-transfer-and-ai-generated-text-detection"
        featured: true
    
      - title: "Arabic Text Formality Modification: A Review and Future Research Directions"
        authors: "Shadi Abudalfa, Fahad Abdu, Maad Alowaifeer"
        year: 2024
        venue: "IEEE Access"
        link: "https://ieeexplore.ieee.org/abstract/document/10778487"
        featured: true
    
      - title: "Two-Stage RFID Approach for Localizing Objects in Smart Homes Based on Gradient Boosted Decision Trees"
        authors: "Shadi Abudalfa, Kevin Bouchard"
        year: 2023
        venue: "Journal of Reliable Intelligent Environments"
        link: "https://link.springer.com/article/10.1007/s40860-022-00199-w"
        featured: true
    
      - title: "Evaluation of Skeletonization Techniques for 2D Binary Images"
        authors: "Shadi Abudalfa"
        year: 2023
        venue: "Informatics and Automation"
        link: "https://ia.spcras.ru/index.php/sp/article/view/15855"
        featured: false
    
      - title: "AT-ODTSA: A Dataset of Arabic Tweets for Open Domain Targeted Sentiment Analysis"
        authors: "Shaaban Sahmoud, Shadi Abudalfa, Wisam Elmasry"
        year: 2022
        venue: "International Journal of Computing and Digital Systemm"
        link: "https://openaccess.iku.edu.tr/entities/publication/6f546db7-f7a2-4d26-8153-d64cc0dd473f"
        featured: false
    
      - title: "Evaluating Performance of Semi-Supervised Clustering with Limited Features for Segmenting Salt Bodies in Seismic Images"
        authors: "Shadi Abudalfa"
        year: 2022
        venue: "International Journal of Academic Multidisciplinary Research"
        link: ""
        featured: false
    
      - title: "Evaluating Performance of Supervised Learning Techniques for Developing Real-Time Intrusion Detection System"
        authors: "Shadi I. Abudalfa, Ekhlas S. Isleem, Marah J. Elshaikh Khalil, Rewaa A. Dalloul, Shaimaa M. Iqtefan"
        year: 2022
        venue: "International Journal of Engineering and Information Systems"
        link: ""
        featured: false
    
      - title: "Semi-Supervised Target-Dependent Sentiment Classification for Micro-Blogs"
        authors: "Shadi Abudalfa, Moataz Ahmed"
        year: 2019
        venue: "Journal of Computer Science & Technology"
        link: "https://sedici.unlp.edu.ar/handle/10915/74462"
        featured: false
    
      - title: "Open Domain Targeted Sentiment Classification Using Semi-Supervised Dynamic Feature Generation"
        authors: "Shadi Abudalfa, Moataz Ahmed"
        year: 2018
        venue: "Journal of Universal Computer Science"
        link: "https://www.researchgate.net/profile/Shadi-Abudalfa/publication/330873022_Open_Domain_Targeted_Sentiment_Classification_Using_Semi-Supervised_Dynamic_Generation_of_Feature_Attributes/links/5caebcf5299bf120975d745d/Open-Domain-Targeted-Sentiment-Classification-Using-Semi-Supervised-Dynamic-Generation-of-Feature-Attributes.pdf"
        featured: true

      - title: "QoS Adaptation for Publish/Subscribe Middleware in Real-Time Dynamic Environments"
        authors: "Basem Almadani, Shadi Abudalfa, Shuang-Hua Yang"
        year: 2017
        venue: "The International Arab Journal of Information Technology"
        link: "https://iajit.org/PDF/Vol%2014,%20No.%202/8606.pdf"
        featured: false

      - title: "K-means algorithm with a novel distance measure"
        authors: "Shadi Abudalfa, Mohammad Mikki"
        year: 2013
        venue: "Turkish Journal of Electrical Engineering and Computer Sciences"
        link: "https://journals.tubitak.gov.tr/elektrik/vol21/iss6/12"
        featured: true

      - title: "A dynamic linkage clustering using KD-tree"
        authors: "Shadi Abudalfa, Mohammad Mikki"
        year: 2013
        venue: "The International Arab Journal of Information Technology"
        link: "https://d1wqtxts1xzle7.cloudfront.net/87297640/11-4246-libre.pdf?1654857534=&response-content-disposition=inline%3B+filename%3DA_Dynamic_Linkage_Clustering_using_KD_Tr.pdf&Expires=1768657050&Signature=NPEIaEPTbpak1-L9wdzggOJN9Baa~rIMufNOviUPAj0Qzq70tR9NqborFut9fjTdCtqpYabTh84FSCQbXIdD~fYnIdBa~R0WpNkhRA3KnWSDjZ1iFsaDp~3o51ZiduFl~TTWkzC~khcDK1xARDeOndUzlH9ujd14wutoC7VUKYbmUBdmYSwfjOayTvgAvxJdu1x4OAC47HIEeHIrvATlHtzwB4YSvC7ZUcGkj8rNiWVBjhjxTdfMx71xYR8WoYwQxfJhHfDpHvt6MJbTNJaa22I3Y9MK1gTEAcItxV3~W4wSgzKj1iL9-Agnay-u3OxzCXHsc-QUEg9lxvi4vXMbgA__&Key-Pair-Id=APKAJLOHF5GGSLRBV4ZA"
        featured: true
        
      - title: "Adaptive Mobility Management Scheme for Mobile IP using Ad Hoc Networks"
        authors: "Hatem Hamad, Shadi Abudalfa, Shaaban Sahmoud"
        year: 2011
        venue: "The International Arab Journal of Information Technology"
        link: "https://www.researchgate.net/profile/Shadi-Abudalfa/publication/220610527_Adaptive_Mobility_Management_Scheme_for_Mobile_IP_using_Ad_Hoc_Networks/links/5528d91b0cf29b22c9bcba07/Adaptive-Mobility-Management-Scheme-for-Mobile-IP-using-Ad-Hoc-Networks.pdf"
        featured: false
    
      # ======================
      # Conference Papers
      # ======================
    
      - title: "Entity Sentiment Classification Using Arabic Lightweight LLMs"
        authors: "Muhammad Raza, Shadi Abudalfa"
        year: 2025
        venue: "International Conference on Engineering and Computing Technologies (EngiTek)"
        link: ""
        featured: false
    
      - title: "Leveraging CLIP for Human Activity Recognition Using UWB Radar Data"
        authors: "Shadi Abudalfa, Kevin Bouchard"
        year: 2025
        venue: "17th International Conference on Ubiquitous Computing and Ambient Intelligence (UCAmI)"
        link: ""
        featured: false
    
      - title: "The AraGenEval Shared Task on Arabic Authorship Style Transfer and AI-Generated Text Detection"
        authors: "Shadi Abudalfa et al."
        year: 2025
        venue: "Third Arabic Natural Language Processing Conference (ArabicNLP)"
        link: "https://aclanthology.org/2025.arabicnlp-sharedtasks.1"
        featured: false
    
      - title: "Lightweight Uni-Domain Model for Human Activity Recognition Using UWB Radars"
        authors: "Shadi Abudalfa, Kevin Bouchard"
        year: 2025
        venue: "ACM International Conference on Information Technology for Social Good (GoodIT)"
        link: ""
        featured: false
    
      - title: "Filtering Data from Motion Sensors with Rich Features for Monitoring Brushing Behaviors"
        authors: "Shadi Abudalfa, Kevin Bouchard"
        year: 2024
        venue: "16th International Conference on Ubiquitous Computing and Ambient Intelligence (UCAmI)"
        link: ""
        featured: false
    
      - title: "Machine Learning for Early Detection of Type 2 Diabetes Based on Liver Enzymes and BMI"
        authors: "Maali Alkhaldi et al., Shadi Abudalfa"
        year: 2024
        venue: "International Conference on Business and Digital Technology (ICBDT)"
        link: ""
        featured: false
    
      - title: "Comparative Study on PaLM and CAMeLBERT for Arabic Entity Sentiment Classification"
        authors: "Salman Almutrash, Shadi Abudalfa"
        year: 2024
        venue: "Saudi Conference on Information Systems (SaudiCIS)"
        link: ""
        featured: false
    
      # ======================
      # Patent
      # ======================
    
      - title: "Open Domain Targeted Sentiment Classification Using Semi-Supervised Dynamic Generation of Feature Attributes"
        authors: "Shadi Abudalfa, Moataz Ahmed"
        year: 2022
        venue: "U.S. Patent No. 11,227,120"
        link: ""
        featured: false
    
      # ======================
      # Book
      # ======================
    
      - title: "Metaheuristic Clustering Algorithm"
        authors: "Shadi Abudalfa"
        year: 2011
        venue: "LAP LAMBERT Academic Publishing"
        link: ""
        featured: false
